version: "3.9"

services:
  app:
    container_name: api1
    build: .
    ports:
      - 3001:3000
    volumes:
      - data-json:/app/data
  app2:
    container_name: api2
    build: .
    ports:
      - 3002:3000
    volumes:
      - data-json:/app/data
volumes:
  data-json: